-- Criação das tabelas do sistema de bar
-- Este script roda automaticamente quando o container sobe pela primeira vez

CREATE TABLE IF NOT EXISTS CATEGORIA (
    ID_CATEGORIA SERIAL PRIMARY KEY,
    DESCRICAO    VARCHAR(100) NOT NULL
);

CREATE TABLE IF NOT EXISTS PRODUTO (
    ID_PRODUTO     SERIAL PRIMARY KEY,
    NOME           VARCHAR(255)   NOT NULL,
    PRECO_UNITARIO NUMERIC(10, 2) NOT NULL,
    FK_CATEGORIA   INT REFERENCES CATEGORIA (ID_CATEGORIA)
);

CREATE TABLE IF NOT EXISTS MESA (
    ID_MESA SERIAL PRIMARY KEY,
    NUMERO  INT         UNIQUE NOT NULL,
    STATUS  VARCHAR(20) DEFAULT 'Disponivel'
);

CREATE TABLE IF NOT EXISTS PEDIDO (
    ID_PEDIDO   SERIAL PRIMARY KEY,
    DATA_HORA   TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FK_MESA     INT            REFERENCES MESA (ID_MESA),
    VALOR_TOTAL NUMERIC(10, 2)
);

CREATE TABLE IF NOT EXISTS USUARIO (
    ID_USUARIO  SERIAL PRIMARY KEY,
    NOME        VARCHAR(100) NOT NULL,
    LOGIN       VARCHAR(50)  UNIQUE NOT NULL,
    SENHA_HASH  TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS ITENS_PEDIDO (
    FK_PEDIDO  INT REFERENCES PEDIDO (ID_PEDIDO),
    FK_PRODUTO INT REFERENCES PRODUTO (ID_PRODUTO),
    QUANTIDADE INT NOT NULL,
    PRIMARY KEY (FK_PEDIDO, FK_PRODUTO)
);
